name: ergonomic-analysis
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: python web_app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  envs:
  - key: FLASK_ENV
    value: production
  - key: FLASK_SECRET_KEY
    value: your-secret-key-here
  - key: PYTHONUNBUFFERED
    value: "1"
storage:
- name: app-storage
  size: 10GB
  mount_path: /app/data